// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-w3_EVTsxdCYeBEITu2dOqu1De8Q2m_4',
    appId: '1:815985929308:android:cc39afc60095a8dd070a99',
    messagingSenderId: '815985929308',
    projectId: 'cafeapp-352be',
    storageBucket: 'cafeapp-352be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChkAP7EylS86CcLMGrDwEByerghOl0jMU',
    appId: '1:815985929308:ios:7a7bd0086634f518070a99',
    messagingSenderId: '815985929308',
    projectId: 'cafeapp-352be',
    storageBucket: 'cafeapp-352be.firebasestorage.app',
    iosBundleId: 'com.ralfiz.cafeApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH6Hx96gB2FPRyDZwDys37DyEz0eHZ9cg',
    appId: '1:815985929308:web:d90fd3e80fc31cbd070a99',
    messagingSenderId: '815985929308',
    projectId: 'cafeapp-352be',
    authDomain: 'cafeapp-352be.firebaseapp.com',
    storageBucket: 'cafeapp-352be.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChkAP7EylS86CcLMGrDwEByerghOl0jMU',
    appId: '1:815985929308:ios:7a7bd0086634f518070a99',
    messagingSenderId: '815985929308',
    projectId: 'cafeapp-352be',
    storageBucket: 'cafeapp-352be.firebasestorage.app',
    iosBundleId: 'com.ralfiz.cafeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH6Hx96gB2FPRyDZwDys37DyEz0eHZ9cg',
    appId: '1:815985929308:web:ba0cd4b2b86b13a2070a99',
    messagingSenderId: '815985929308',
    projectId: 'cafeapp-352be',
    authDomain: 'cafeapp-352be.firebaseapp.com',
    storageBucket: 'cafeapp-352be.firebasestorage.app',
  );

}